### ISSUE TITLE
Mirror image inversion

### ISSUE THREAD

**Issue by dankarlin** [GregDMeyer/IT8951#25]
Writing an image to the screen using the function display_image_8bpp from the test_functions, the image is left/right transposed. Rotation and flipping just re-orient the mirror image.

**Comment by GregDMeyer** [comment]
Sorry for the delay in responding to this---unfortunately I can't reproduce the bug; on my device the image is displayed correctly when I call that function. Have you figured out the problem since you opened the issue? If you have more details I'm happy to reopen the issue and try to get to the bottom of it!

**Comment by Mari0nV** [comment]
I got the same issue, I don't know why.
I fixed it by replacing the function *_get_frame_buf* in *display.py* by:
```
def _get_frame_buf(self):
        return self.frame_buf.transpose(Image.FLIP_LEFT_RIGHT)
```

**Comment by GregDMeyer** [comment]
That is so strange. Let me know if you find out any further why this is happening, it's so weird that it only happens for a few people!
